name: ROS2 image release

on:
  release:
    types: [published]

jobs:
  release:
    uses: ./.github/workflows/builder.yaml
    with:
      ros_distro: jazzy
      environment: production
    secrets: inherit